//交互
$(function(){
    //header 切换模式点击事件
    $('header').on('click','a',function(e){
        e.preventDefault();
        $(e.target).addClass('active').siblings().removeClass('active').css('text-decoration','none');
    });
    $('section ul>li').on('click','a',function(e){
        e.preventDefault();
        $(e.target).parent().toggleClass('active').siblings().removeClass('active');
    });
    //不限超链接的点击事件
    $('#limit').on('click','li.all>a',function(e){
        e.preventDefault();
        $('#more .total').css('display','none');//区域隐藏
    });
    //section 展开按钮的点击事件
    $('#more').on('click','#bb',function(e){
        var html=`
          收起<img src="./res/up-disabled.png"/>
        `;
        $('#bb').html(html);
        $('#bb').toggleClass('up').parent().parent().next().css('display','block');//区域显示
        $('#limit>li.city:gt(12)').css('display','block');
    });
    //收起按钮点击事件
    $('#more').on('click','a.up',function(e){
        $('#bb').parent().parent().next().css('display','none');//区域隐藏
        var html=`
          更多<img src="./res/down.png"/>
        `;
        $('#bb').html(html);
        $('#limit>li.city:gt(12)').css('display','none');

    });
});
//土地列表_及模糊查询
$(function(){
    //跳转成功后异步请求详情数据
    var PageNum=1	,//是	string	//当前页
        PageSize=20	,//是	string	//每页大小
        pageSize,//最大页码数
        Search=''	,//否	string	//搜寻条件
        CityID=''	,//否	string	//城市id
        BoroughID='',//否	string	//区域id
        PlateID=''	,//否	string	//板块id
        Purpose=''	,//否	string	//全部为空 1为住宅 2为商业 3为酒店
        State=''	,//否	string	//全部为空 1为未成交 2流拍 3已成交
        Px=0;	//是	string	// 排序 0 默认排序 1 土地面积升序 2 土地面积降序 3 所属地区升序 4 所属地区降序 5 时间升序 6时间降序 7 起始价升序 8 起始价降序
    //页码
    function page(){
        $.ajax({
            url:saleUrl+'landlist_version2.do',
            data:{
                pageNum:PageNum	,//是	string	//当前页
                pageSize:PageSize	,//是	string	//每页大小
                search:Search	,//否	string	//搜寻条件
                cityID:CityID	,//否	string	//城市id
                boroughID:BoroughID	,//否	string	//区域id
                plateID:PlateID	,//否	string	//板块id
                purpose:Purpose	,//否	string	//全部为空 1为住宅 2为商业 3为酒店
                state:State	,//否	string	//全部为空 1为未成交 2流拍 3已成交
                px:Px	//是	string	// 排序 0 默认排序 1 土地面积升序 2 土地面积降序 3 所属地区升序 4 所属地区降序 5 时间升序 6时间降序 7 起始价升序 8 起始价降序
            },
            type:'POST',
            success:function(data){
                if(data==''){
                    return;
                }
                //console.log(data);
                var floorList=data.data.landList;//列表数据
                var listHtml='',theadHtml='';
                //判断列表数据内容为空
                if(!floorList||floorList.length==0||data.data.size==0){
                    $('#items>tbody').html(' ');
                    //thead数据
                    theadHtml+=`
                      区域 <span>(0)</span>
                    `;

                }else{
                    $.each(floorList,function(i){
                        //土地状态
                        function LandState(t){
                            switch(t)
                            {
                                case 1:
                                    return t = "未成交";
                                    break;
                                case 2:
                                    return t = "流拍";
                                    break;
                                case 3:
                                    return t = "已成交";
                                    break;
                                default:
                                    return t = "其他";
                                    break;
                            }
                        }
                        //规划用途
                        function PlanningPurposes(t){
                            switch(t)
                            {
                                case 1:
                                    return t = "别墅";
                                    break;
                                case 2:
                                    return t = "住宅";
                                    break;
                                case 3:
                                    return t = "商铺";
                                    break;
                                case 4:
                                    return t = "商住";
                                    break;
                                case 5:
                                    return t = "其他";
                                    break;
                                default:
                                    return t = "其他";
                                    break;
                            }
                        }
                        //console.log(LandState(floorList[i].LandState));
                        //动态添加
                        var LandStateHtml=`
                          <a href="#" class="landState">${LandState(floorList[i].LandState)}</a>
                        `;
                        var soldHtml=`
                      <a href="#" class="planningPurposes">${PlanningPurposes(floorList[i].PlanningPurposes)}</a>
                    `;
                        var saleHtml=`
                       <a href="#">拍卖</a>
                    `;
                        var statesHtml=LandStateHtml+soldHtml+saleHtml;
                        //$('#items>tbody .states').html(statesHtml);
                        if(!floorList[i].PlanningPurposes){
                            statesHtml=LandStateHtml+saleHtml;
                        }
                        if(!floorList[i].LandState){
                            statesHtml=soldHtml+saleHtml;
                        }
                        if(!floorList[i].PlanningPurposes&&!floorList[i].LandState){
                            statesHtml=saleHtml;
                        }
                        if(!floorList[i].Cityname){
                            floorList[i].Cityname='';
                        }
                        if(!floorList[i].Boroughname){
                            floorList[i].Boroughname='';
                        }
                        //tbody数据
                        listHtml+=`
                         <tr id="${floorList[i].id}">
                            <td>
                                <div class="gt">
                                    <div class="states">
                                        ${statesHtml}
                                    </div>
                                </div>
                                <h4>${floorList[i].LandName}</h4>
                            </td>
                            <td>${floorList[i].PlotArea}</td>
                            <td>${floorList[i].PlanArea}</td>
                            <td id='${floorList[i].CityID}' class="${floorList[i].BoroughID}">${floorList[i].Cityname}-${floorList[i].Boroughname}</td>
                            <td>${floorList[i].LaunchTime}</td>
                            <td>${floorList[i].StartingPrice}</td>
                         </tr>
                    `;
                        $('#items>tbody').html(listHtml);
                    });
                    //thead数据
                    theadHtml+=`
                      区域 <span>(${data.data.size})</span>
                    `;

                }
                $('#floorCount').html(theadHtml);

                //页码
                var pageHtml='',moreHtml='',styleHtml='';
                pageSize=Math.ceil(data.data.size/20);//获取页码最大值
                //循环拼接字符串，生成翻页功能
                if(pageSize==0){
                    pageSize=1;
                }
                if(pageSize<7){
                    for(var i=1;i<=pageSize;i++){
                        pageHtml+=`
                          <li><a href="#" class="${i}">${i}</a></li>
                        `;
                    }
                    $('#pageNum').html(pageHtml);
                }else{
                    styleHtml+=`
                  <li><a href="#" class="1">1</a></li>
                  <li><a href="#" class="2">2</a></li>
                  <li><a href="#" class="3">3</a></li>
                  <li><a href="#" class="4">4</a></li>
                  <li class="more"><a href="#">...</a></li>
                  <li><a href="#" class="${pageSize}">${pageSize}</a></li>
                `;
                    $('#pageNum').html(styleHtml);
                    for(var j=5;j<pageSize;j++){
                        moreHtml+=`
                          <li><a href="#" class="${j}">${j}</a></li>
                        `;
                    }
                    $('#pageNum>li.more').on('click','a',function(e){
                        e.preventDefault();
                        $(e.target).parent().after(moreHtml);//显示所有页码
                        $(e.target).parent().css('display','none');//...隐藏
                        $('#pageNum>li:nth-child(1)').addClass('active').siblings().removeClass('active');//第四页加.active
                    });
                }
                $('#pageNum>li>a.'+PageNum).parent().addClass('active');
                //判断当前页码，决定.more的显示隐藏
                if(PageNum>4){
                    $('#pageNum>li.more').hide().after(moreHtml);
                    $('#pageNum>li>a.'+PageNum).parent().addClass('active');
                }
            },
            error:function(){
                alert('服务器内部出错了')
            }
        });
    }
    page();
    //页码数的点击事件
    $('#pageNum').on('click','li:not(.more)>a',function(e){
        e.preventDefault();
        $(e.target).parent().addClass('active').siblings().removeClass('active');
        PageNum=$(e.target).html();//获取当前页码
        if(PageNum==1){
            $('#pages>ul>li.prev').addClass('disabled').siblings().removeClass('disabled');
        }else{
            $('#pages>ul>li.prev').removeClass('disabled');
        }
        if(PageNum==pageSize){
            $('#pages>ul>li.next').addClass('disabled').siblings().removeClass('disabled');
        }else{
            $('#pages>ul>li.next').removeClass('disabled');
        }
        page();
    });
    //向前翻页按钮的点击事件
    $('#pages>ul>li.next').on('click','a',function(e){
        e.preventDefault();
        var moreHtml='';
        PageNum++;
        $('#pageNum>li.active').removeClass('active').next().addClass('active');//为下一页加.active
        $('#pages>ul>li.prev').removeClass('disabled');
        for(var j=5;j<pageSize;j++){
            moreHtml+=`
                          <li><a href="#" class="${j}">${j}</a></li>
                        `;
        }
        if(PageNum==5){
            $('#pageNum>li.more').hide().after(moreHtml);//显示所有页码;
            $('#pageNum>li.active').removeClass('active').next().addClass('active');//为下一页加.active
        }
        if(PageNum>=pageSize){
            PageNum=pageSize;
            $('#pages>ul>li.next').addClass('disabled');
        }
        page();
    });
    //向后翻页的点击事件
    $('#pages>ul>li.prev').on('click','a',function(e){
        e.preventDefault();
        PageNum--;
        $('#pageNum>li.active').removeClass('active').prev().addClass('active');//为下一页加.active
        $('#pages>ul>li.next').removeClass('disabled');
        if(PageNum==4){
            $('#pageNum>li.active').removeClass('active').prev().addClass('active');
        }
        if(PageNum<=1){
            PageNum=1;
            $('#pages>ul>li.prev').addClass('disabled');
        }
        page();
    });
    //规划用途筛选条件
    $('#purpose>li').on('click','a',function(e){
        var selfPage=page;
        e.preventDefault();
        if($(e.target).html()=='别墅'){
            Purpose=1;
            selfPage();
        }
        if($(e.target).html()=='住宅'){
            Purpose=2;
            selfPage();
        }
        if($(e.target).html()=='商铺'){
            Purpose=3;
            selfPage();
        }
        if($(e.target).html()=='商住'){
            Purpose=4;
            selfPage();
        }
        if($(e.target).html()=='其他'){
            Purpose=5;
            selfPage();
        }
    });
    //规划用途不限
    $('#purpose').on('click','a.all',function(e){
        e.preventDefault();
        Purpose='';
        page();
    });
    //土地状态筛选条件
    $('#state>li').on('click','a',function(e){
        e.preventDefault();
        var selfPage=page;
        if($(e.target).html()=='未成交'){
            State=1;
            selfPage();
        }
        if($(e.target).html()=='流拍'){
            State=2;
            selfPage();
        }
        if($(e.target).html()=='已成交'){
            State=3;
            selfPage();
        }
    });
    //土地状态不限
    $('#state').on('click','a.all',function(e){
        e.preventDefault();
        State='';
        page();
    });
    //城市筛选条件
    $('#limit').on('click','li.city>a',function(e){
        e.preventDefault();
        CityID=$(e.target).attr('id');
        BoroughID='';
        PlateID='';
        page();
    });
    //城市不限按钮的点击事件
    $('#limit').on('click','li.all>a',function(e){
        e.preventDefault();
        CityID='';
        BoroughID='';
        PlateID='';
        page();
    });
    //区域筛选条件
    $('#borough').on('click','li.borough>a',function(e){
        e.preventDefault();
        BoroughID=$(e.target).attr('id');
        PlateID='';
        page();
    });
    //区域全部链接点击事件
    $('#borough').on('click','a.all',function(e){
        e.preventDefault();
        $('#borough>li').removeClass('active');
        CityID=$('#limit>li.active>a').attr('id');
        BoroughID='';
        PlateID='';
        page();
    });
    //板块筛选条件
    $('#plateTotal').on('click','li.plate>a',function(e){
        e.preventDefault();
        PlateID=$(e.target).attr('id');
        page();
    });
    //表头a标记点击阻止默认行为
    $('#items>thead').on('click','a',function(e){
        e.preventDefault();
    });
    //楼盘列表中土地面积点击上下箭头实现排序功能
    $('#items>thead').on('click','.up-img',function(e){
        $(e.target).attr('src','./res/up-disabled-a.png');
        $(e.target).next().attr('src','./res/down-disabled.png');
    }).on('click','.down-img',function(e){
        $(e.target).prev().attr('src','./res/up-disabled.png');
        $(e.target).attr('src','./res/down-disabled-a.png');
    });
    $('#items>thead').on('click','tr>th:nth-child(2) .up-img',function(e){
        e.preventDefault();
        Px=9;
        page();
    })
    .on('click','tr>th:nth-child(2) .down-img',function(e){
            e.preventDefault();
            Px=10;
            page();
        });
    //楼盘列表中规划面积点击上下箭头实现排序功能
    $('#items>thead').on('click','tr>th:nth-child(3) .up-img',function(e){
        e.preventDefault();
        Px=1;
        page();
    })
        .on('click','tr>th:nth-child(3) .down-img',function(e){
            e.preventDefault();
            Px=2;
            page();
        });
    //楼盘列表中所属地区点击上下箭头实现排序功能
    $('#items>thead').on('click','tr>th:nth-child(4) .up-img',function(e){
        e.preventDefault();
        Px=3;
        page();
    })
        .on('click','tr>th:nth-child(4) .down-img',function(e){
            e.preventDefault();
            Px=4;
            page();
        });
    //楼盘列表中时间点击上下箭头实现排序功能
    $('#items>thead').on('click','tr>th:nth-child(5) .up-img',function(e){
        e.preventDefault();
        Px=5;
        page();
    })
        .on('click','tr>th:nth-child(5) .down-img',function(e){
            e.preventDefault();
            Px=6;
            page();
        });
    //楼盘列表中起始价点击上下箭头实现排序功能
    $('#items>thead').on('click','tr>th:last-child .up-img',function(e){
        e.preventDefault();
        Px=7;
        page();
    })
        .on('click','tr>th:last-child .down-img',function(e){
            e.preventDefault();
            Px=8;
            page();
        });
    //搜索框的模糊查询
    $('#search>form>div>span').on('click','img',function(){
        Search=$('#appendedInput').val();
        page();
    });
    //tobody>tr点击跳转详情
    $('#items>tbody').on('click','tr>td',function(e){
        if($(e.target).context.localName=='td'){
            var id=$(e.target).parent().attr('id');
            $(location).attr('href','./landDetail.html?id='+id);
        }else{
            e.preventDefault();
            return;
        }
    });
});
//土地热门城市，区域，板块
$(function(){
    function city(){
        $.ajax({
            url:saleUrl+'getHotCity.do',
            type:'POST',
            success:function(data){
                //console.log(data);
                var citiesHtml='',limitCity;
                //城市内容动态添加
                limitCity=data.data;
                if(!limitCity){
                    return;
                }
                $.each(limitCity,function(i){
                    citiesHtml+=`
                           <li class="city"><a href="#" id="${limitCity[i].ID}">${limitCity[i].CityName}</a></li>
                        `;
                });
                var allHtml=`
                      <li class="all active"><a href="#">不限</a></li>
                    `;
                $('#limit').html(allHtml+citiesHtml);
                //热门城市一行定14个，超过的默认隐藏
                if ($('#limit>li.city').size() > 14) {
                    $('#limit>li.city:gt(13)').css('display', 'none');
                }else{
                    $('#more li.extend').hide();
                }
                //城市超链接的点击事件
                $('#limit').on('click','li.city>a',function(e){
                    e.preventDefault();
                    $('#more>ul.total').css('display','block');//区域显示
                });
            },
            error:function(){
                alert('服务器内部出错了')
            }
        });
    }
    city();
    //异步请求区域数据
    $('#limit').on('click','li.city>a',function(e){
        e.preventDefault();
        var cityId=$(e.target).attr('id'); //城市点击获取其id
        //console.log(cityId);
        $.ajax({
            url:saleUrl+'getHotBorough.do',
            type:'POST',
            data:{
                cityId:cityId	//是	string	城市ID
            },
            success:function(data){
                //console.log(data);
                //区域内容动态添加
                var boroughHtml='',limitBorough;
                limitBorough=data.data;
                if(!limitBorough){
                    return;
                }
                $.each(limitBorough,function(i){
                    boroughHtml+=`
                           <li class="borough"><a href="#" id="${limitBorough[i].ID}">${limitBorough[i].BoroughName}</a></li>
                         `;
                });
                var allHtml=`
                      <li class="active"><a href="#" class="all">全部</a></li>
                `;
                $('#borough').html(allHtml+boroughHtml);
                //板块的显示与隐藏
                $('#borough').on('click','li.borough>a',function(e){
                    e.preventDefault();
                    $('#plate').show();
                });
            },
            error:function(){
                alert('服务器内部出错了')
            }
        });
    });
    //板块内容的动态生成
    var strChineseFirstPY = "YDYQSXMWZSSXJBYMGCCZQPSSQBYCDSCDQLDYLYBSSJGYZZJJFKCCLZDHWDWZJLJPFYYNWJJTMYHZWZHFLZPPQHGSCYYYNJQYXXGJHHSDSJNKKTMOMLCRXYPSNQSECCQZGGLLYJLMYZZSECYKYYHQWJSSGGYXYZYJWWKDJHYCHMYXJTLXJYQBYXZLDWRDJRWYSRLDZJPCBZJJBRCFTLECZSTZFXXZHTRQHYBDLYCZSSYMMRFMYQZPWWJJYFCRWFDFZQPYDDWYXKYJAWJFFXYPSFTZYHHYZYSWCJYXSCLCXXWZZXNBGNNXBXLZSZSBSGPYSYZDHMDZBQBZCWDZZYYTZHBTSYYBZGNTNXQYWQSKBPHHLXGYBFMJEBJHHGQTJCYSXSTKZHLYCKGLYSMZXYALMELDCCXGZYRJXSDLTYZCQKCNNJWHJTZZCQLJSTSTBNXBTYXCEQXGKWJYFLZQLYHYXSPSFXLMPBYSXXXYDJCZYLLLSJXFHJXPJBTFFYABYXBHZZBJYZLWLCZGGBTSSMDTJZXPTHYQTGLJSCQFZKJZJQNLZWLSLHDZBWJNCJZYZSQQYCQYRZCJJWYBRTWPYFTWEXCSKDZCTBZHYZZYYJXZCFFZZMJYXXSDZZOTTBZLQWFCKSZSXFYRLNYJMBDTHJXSQQCCSBXYYTSYFBXDZTGBCNSLCYZZPSAZYZZSCJCSHZQYDXLBPJLLMQXTYDZXSQJTZPXLCGLQTZWJBHCTSYJSFXYEJJTLBGXSXJMYJQQPFZASYJNTYDJXKJCDJSZCBARTDCLYJQMWNQNCLLLKBYBZZSYHQQLTWLCCXTXLLZNTYLNEWYZYXCZXXGRKRMTCNDNJTSYYSSDQDGHSDBJGHRWRQLYBGLXHLGTGXBQJDZPYJSJYJCTMRNYMGRZJCZGJMZMGXMPRYXKJNYMSGMZJYMKMFXMLDTGFBHCJHKYLPFMDXLQJJSMTQGZSJLQDLDGJYCALCMZCSDJLLNXDJFFFFJCZFMZFFPFKHKGDPSXKTACJDHHZDDCRRCFQYJKQCCWJDXHWJLYLLZGCFCQDSMLZPBJJPLSBCJGGDCKKDEZSQCCKJGCGKDJTJDLZYCXKLQSCGJCLTFPCQCZGWPJDQYZJJBYJHSJDZWGFSJGZKQCCZLLPSPKJGQJHZZLJPLGJGJJTHJJYJZCZMLZLYQBGJWMLJKXZDZNJQSYZMLJLLJKYWXMKJLHSKJGBMCLYYMKXJQLBMLLKMDXXKWYXYSLMLPSJQQJQXYXFJTJDXMXXLLCXQBSYJBGWYMBGGBCYXPJYGPEPFGDJGBHBNSQJYZJKJKHXQFGQZKFHYGKHDKLLSDJQXPQYKYBNQSXQNSZSWHBSXWHXWBZZXDMNSJBSBKBBZKLYLXGWXDRWYQZMYWSJQLCJXXJXKJEQXSCYETLZHLYYYSDZPAQYZCMTLSHTZCFYZYXYLJSDCJQAGYSLCQLYYYSHMRQQKLDXZSCSSSYDYCJYSFSJBFRSSZQSBXXPXJYSDRCKGJLGDKZJZBDKTCSYQPYHSTCLDJDHMXMCGXYZHJDDTMHLTXZXYLYMOHYJCLTYFBQQXPFBDFHHTKSQHZYYWCNXXCRWHOWGYJLEGWDQCWGFJYCSNTMYTOLBYGWQWESJPWNMLRYDZSZTXYQPZGCWXHNGPYXSHMYQJXZTDPPBFYHZHTJYFDZWKGKZBLDNTSXHQEEGZZYLZMMZYJZGXZXKHKSTXNXXWYLYAPSTHXDWHZYMPXAGKYDXBHNHXKDPJNMYHYLPMGOCSLNZHKXXLPZZLBMLSFBHHGYGYYGGBHSCYAQTYWLXTZQCEZYDQDQMMHTKLLSZHLSJZWFYHQSWSCWLQAZYNYTLSXTHAZNKZZSZZLAXXZWWCTGQQTDDYZTCCHYQZFLXPSLZYGPZSZNGLNDQTBDLXGTCTAJDKYWNSYZLJHHZZCWNYYZYWMHYCHHYXHJKZWSXHZYXLYSKQYSPSLYZWMYPPKBYGLKZHTYXAXQSYSHXASMCHKDSCRSWJPWXSGZJLWWSCHSJHSQNHCSEGNDAQTBAALZZMSSTDQJCJKTSCJAXPLGGXHHGXXZCXPDMMHLDGTYBYSJMXHMRCPXXJZCKZXSHMLQXXTTHXWZFKHCCZDYTCJYXQHLXDHYPJQXYLSYYDZOZJNYXQEZYSQYAYXWYPDGXDDXSPPYZNDLTWRHXYDXZZJHTCXMCZLHPYYYYMHZLLHNXMYLLLMDCPPXHMXDKYCYRDLTXJCHHZZXZLCCLYLNZSHZJZZLNNRLWHYQSNJHXYNTTTKYJPYCHHYEGKCTTWLGQRLGGTGTYGYHPYHYLQYQGCWYQKPYYYTTTTLHYHLLTYTTSPLKYZXGZWGPYDSSZZDQXSKCQNMJJZZBXYQMJRTFFBTKHZKBXLJJKDXJTLBWFZPPTKQTZTGPDGNTPJYFALQMKGXBDCLZFHZCLLLLADPMXDJHLCCLGYHDZFGYDDGCYYFGYDXKSSEBDHYKDKDKHNAXXYBPBYYHXZQGAFFQYJXDMLJCSQZLLPCHBSXGJYNDYBYQSPZWJLZKSDDTACTBXZDYZYPJZQSJNKKTKNJDJGYYPGTLFYQKASDNTCYHBLWDZHBBYDWJRYGKZYHEYYFJMSDTYFZJJHGCXPLXHLDWXXJKYTCYKSSSMTWCTTQZLPBSZDZWZXGZAGYKTYWXLHLSPBCLLOQMMZSSLCMBJCSZZKYDCZJGQQDSMCYTZQQLWZQZXSSFPTTFQMDDZDSHDTDWFHTDYZJYQJQKYPBDJYYXTLJHDRQXXXHAYDHRJLKLYTWHLLRLLRCXYLBWSRSZZSYMKZZHHKYHXKSMDSYDYCJPBZBSQLFCXXXNXKXWYWSDZYQOGGQMMYHCDZTTFJYYBGSTTTYBYKJDHKYXBELHTYPJQNFXFDYKZHQKZBYJTZBXHFDXKDASWTAWAJLDYJSFHBLDNNTNQJTJNCHXFJSRFWHZFMDRYJYJWZPDJKZYJYMPCYZNYNXFBYTFYFWYGDBNZZZDNYTXZEMMQBSQEHXFZMBMFLZZSRXYMJGSXWZJSPRYDJSJGXHJJGLJJYNZZJXHGXKYMLPYYYCXYTWQZSWHWLYRJLPXSLSXMFSWWKLCTNXNYNPSJSZHDZEPTXMYYWXYYSYWLXJQZQXZDCLEEELMCPJPCLWBXSQHFWWTFFJTNQJHJQDXHWLBYZNFJLALKYYJLDXHHYCSTYYWNRJYXYWTRMDRQHWQCMFJDYZMHMYYXJWMYZQZXTLMRSPWWCHAQBXYGZYPXYYRRCLMPYMGKSJSZYSRMYJSNXTPLNBAPPYPYLXYYZKYNLDZYJZCZNNLMZHHARQMPGWQTZMXXMLLHGDZXYHXKYXYCJMFFYYHJFSBSSQLXXNDYCANNMTCJCYPRRNYTYQNYYMBMSXNDLYLYSLJRLXYSXQMLLYZLZJJJKYZZCSFBZXXMSTBJGNXYZHLXNMCWSCYZYFZLXBRNNNYLBNRTGZQYSATSWRYHYJZMZDHZGZDWYBSSCSKXSYHYTXXGCQGXZZSHYXJSCRHMKKBXCZJYJYMKQHZJFNBHMQHYSNJNZYBKNQMCLGQHWLZNZSWXKHLJHYYBQLBFCDSXDLDSPFZPSKJYZWZXZDDXJSMMEGJSCSSMGCLXXKYYYLNYPWWWGYDKZJGGGZGGSYCKNJWNJPCXBJJTQTJWDSSPJXZXNZXUMELPXFSXTLLXCLJXJJLJZXCTPSWXLYDHLYQRWHSYCSQYYBYAYWJJJQFWQCQQCJQGXALDBZZYJGKGXPLTZYFXJLTPADKYQHPMATLCPDCKBMTXYBHKLENXDLEEGQDYMSAWHZMLJTWYGXLYQZLJEEYYBQQFFNLYXRDSCTGJGXYYNKLLYQKCCTLHJLQMKKZGCYYGLLLJDZGYDHZWXPYSJBZKDZGYZZHYWYFQYTYZSZYEZZLYMHJJHTSMQWYZLKYYWZCSRKQYTLTDXWCTYJKLWSQZWBDCQYNCJSRSZJLKCDCDTLZZZACQQZZDDXYPLXZBQJYLZLLLQDDZQJYJYJZYXNYYYNYJXKXDAZWYRDLJYYYRJLXLLDYXJCYWYWNQCCLDDNYYYNYCKCZHXXCCLGZQJGKWPPCQQJYSBZZXYJSQPXJPZBSBDSFNSFPZXHDWZTDWPPTFLZZBZDMYYPQJRSDZSQZSQXBDGCPZSWDWCSQZGMDHZXMWWFYBPDGPHTMJTHZSMMBGZMBZJCFZWFZBBZMQCFMBDMCJXLGPNJBBXGYHYYJGPTZGZMQBQTCGYXJXLWZKYDPDYMGCFTPFXYZTZXDZXTGKMTYBBCLBJASKYTSSQYYMSZXFJEWLXLLSZBQJJJAKLYLXLYCCTSXMCWFKKKBSXLLLLJYXTYLTJYYTDPJHNHNNKBYQNFQYYZBYYESSESSGDYHFHWTCJBSDZZTFDMXHCNJZYMQWSRYJDZJQPDQBBSTJGGFBKJBXTGQHNGWJXJGDLLTHZHHYYYYYYSXWTYYYCCBDBPYPZYCCZYJPZYWCBDLFWZCWJDXXHYHLHWZZXJTCZLCDPXUJCZZZLYXJJTXPHFXWPYWXZPTDZZBDZCYHJHMLXBQXSBYLRDTGJRRCTTTHYTCZWMXFYTWWZCWJWXJYWCSKYBZSCCTZQNHXNWXXKHKFHTSWOCCJYBCMPZZYKBNNZPBZHHZDLSYDDYTYFJPXYNGFXBYQXCBHXCPSXTYZDMKYSNXSXLHKMZXLYHDHKWHXXSSKQYHHCJYXGLHZXCSNHEKDTGZXQYPKDHEXTYKCNYMYYYPKQYYYKXZLTHJQTBYQHXBMYHSQCKWWYLLHCYYLNNEQXQWMCFBDCCMLJGGXDQKTLXKGNQCDGZJWYJJLYHHQTTTNWCHMXCXWHWSZJYDJCCDBQCDGDNYXZTHCQRXCBHZTQCBXWGQWYYBXHMBYMYQTYEXMQKYAQYRGYZSLFYKKQHYSSQYSHJGJCNXKZYCXSBXYXHYYLSTYCXQTHYSMGSCPMMGCCCCCMTZTASMGQZJHKLOSQYLSWTMXSYQKDZLJQQYPLSYCZTCQQPBBQJZCLPKHQZYYXXDTDDTSJCXFFLLCHQXMJLWCJCXTSPYCXNDTJSHJWXDQQJSKXYAMYLSJHMLALYKXCYYDMNMDQMXMCZNNCYBZKKYFLMCHCMLHXRCJJHSYLNMTJZGZGYWJXSRXCWJGJQHQZDQJDCJJZKJKGDZQGJJYJYLXZXXCDQHHHEYTMHLFSBDJSYYSHFYSTCZQLPBDRFRZTZYKYWHSZYQKWDQZRKMSYNBCRXQBJYFAZPZZEDZCJYWBCJWHYJBQSZYWRYSZPTDKZPFPBNZTKLQYHBBZPNPPTYZZYBQNYDCPJMMCYCQMCYFZZDCMNLFPBPLNGQJTBTTNJZPZBBZNJKLJQYLNBZQHKSJZNGGQSZZKYXSHPZSNBCGZKDDZQANZHJKDRTLZLSWJLJZLYWTJNDJZJHXYAYNCBGTZCSSQMNJPJYTYSWXZFKWJQTKHTZPLBHSNJZSYZBWZZZZLSYLSBJHDWWQPSLMMFBJDWAQYZTCJTBNNWZXQXCDSLQGDSDPDZHJTQQPSWLYYJZLGYXYZLCTCBJTKTYCZJTQKBSJLGMGZDMCSGPYNJZYQYYKNXRPWSZXMTNCSZZYXYBYHYZAXYWQCJTLLCKJJTJHGDXDXYQYZZBYWDLWQCGLZGJGQRQZCZSSBCRPCSKYDZNXJSQGXSSJMYDNSTZTPBDLTKZWXQWQTZEXNQCZGWEZKSSBYBRTSSSLCCGBPSZQSZLCCGLLLZXHZQTHCZMQGYZQZNMCOCSZJMMZSQPJYGQLJYJPPLDXRGZYXCCSXHSHGTZNLZWZKJCXTCFCJXLBMQBCZZWPQDNHXLJCTHYZLGYLNLSZZPCXDSCQQHJQKSXZPBAJYEMSMJTZDXLCJYRYYNWJBNGZZTMJXLTBSLYRZPYLSSCNXPHLLHYLLQQZQLXYMRSYCXZLMMCZLTZSDWTJJLLNZGGQXPFSKYGYGHBFZPDKMWGHCXMSGDXJMCJZDYCABXJDLNBCDQYGSKYDQTXDJJYXMSZQAZDZFSLQXYJSJZYLBTXXWXQQZBJZUFBBLYLWDSLJHXJYZJWTDJCZFQZQZZDZSXZZQLZCDZFJHYSPYMPQZMLPPLFFXJJNZZYLSJEYQZFPFZKSYWJJJHRDJZZXTXXGLGHYDXCSKYSWMMZCWYBAZBJKSHFHJCXMHFQHYXXYZFTSJYZFXYXPZLCHMZMBXHZZSXYFYMNCWDABAZLXKTCSHHXKXJJZJSTHYGXSXYYHHHJWXKZXSSBZZWHHHCWTZZZPJXSNXQQJGZYZYWLLCWXZFXXYXYHXMKYYSWSQMNLNAYCYSPMJKHWCQHYLAJJMZXHMMCNZHBHXCLXTJPLTXYJHDYYLTTXFSZHYXXSJBJYAYRSMXYPLCKDUYHLXRLNLLSTYZYYQYGYHHSCCSMZCTZQXKYQFPYYRPFFLKQUNTSZLLZMWWTCQQYZWTLLMLMPWMBZSSTZRBPDDTLQJJBXZCSRZQQYGWCSXFWZLXCCRSZDZMCYGGDZQSGTJSWLJMYMMZYHFBJDGYXCCPSHXNZCSBSJYJGJMPPWAFFYFNXHYZXZYLREMZGZCYZSSZDLLJCSQFNXZKPTXZGXJJGFMYYYSNBTYLBNLHPFZDCYFBMGQRRSSSZXYSGTZRNYDZZCDGPJAFJFZKNZBLCZSZPSGCYCJSZLMLRSZBZZLDLSLLYSXSQZQLYXZLSKKBRXBRBZCYCXZZZEEYFGKLZLYYHGZSGZLFJHGTGWKRAAJYZKZQTSSHJJXDCYZUYJLZYRZDQQHGJZXSSZBYKJPBFRTJXLLFQWJHYLQTYMBLPZDXTZYGBDHZZRBGXHWNJTJXLKSCFSMWLSDQYSJTXKZSCFWJLBXFTZLLJZLLQBLSQMQQCGCZFPBPHZCZJLPYYGGDTGWDCFCZQYYYQYSSCLXZSKLZZZGFFCQNWGLHQYZJJCZLQZZYJPJZZBPDCCMHJGXDQDGDLZQMFGPSYTSDYFWWDJZJYSXYYCZCYHZWPBYKXRYLYBHKJKSFXTZJMMCKHLLTNYYMSYXYZPYJQYCSYCWMTJJKQYRHLLQXPSGTLYYCLJSCPXJYZFNMLRGJJTYZBXYZMSJYJHHFZQMSYXRSZCWTLRTQZSSTKXGQKGSPTGCZNJSJCQCXHMXGGZTQYDJKZDLBZSXJLHYQGGGTHQSZPYHJHHGYYGKGGCWJZZYLCZLXQSFTGZSLLLMLJSKCTBLLZZSZMMNYTPZSXQHJCJYQXYZXZQZCPSHKZZYSXCDFGMWQRLLQXRFZTLYSTCTMJCXJJXHJNXTNRZTZFQYHQGLLGCXSZSJDJLJCYDSJTLNYXHSZXCGJZYQPYLFHDJSBPCCZHJJJQZJQDYBSSLLCMYTTMQTBHJQNNYGKYRQYQMZGCJKPDCGMYZHQLLSLLCLMHOLZGDYYFZSLJCQZLYLZQJESHNYLLJXGJXLYSYYYXNBZLJSSZCQQCJYLLZLTJYLLZLLBNYLGQCHXYYXOXCXQKYJXXXYKLXSXXYQXCYKQXQCSGYXXYQXYGYTQOHXHXPYXXXULCYEYCHZZCBWQBBWJQZSCSZSSLZYLKDESJZWMYMCYTSDSXXSCJPQQSQYLYYZYCMDJDZYWCBTJSYDJKCYDDJLBDJJSODZYSYXQQYXDHHGQQYQHDYXWGMMMAJDYBBBPPBCMUUPLJZSMTXERXJMHQNUTPJDCBSSMSSSTKJTSSMMTRCPLZSZMLQDSDMJMQPNQDXCFYNBFSDQXYXHYAYKQYDDLQYYYSSZBYDSLNTFQTZQPZMCHDHCZCWFDXTMYQSPHQYYXSRGJCWTJTZZQMGWJJTJHTQJBBHWZPXXHYQFXXQYWYYHYSCDYDHHQMNMTMWCPBSZPPZZGLMZFOLLCFWHMMSJZTTDHZZYFFYTZZGZYSKYJXQYJZQBHMBZZLYGHGFMSHPZFZSNCLPBQSNJXZSLXXFPMTYJYGBXLLDLXPZJYZJYHHZCYWHJYLSJEXFSZZYWXKZJLUYDTMLYMQJPWXYHXSKTQJEZRPXXZHHMHWQPWQLYJJQJJZSZCPHJLCHHNXJLQWZJHBMZYXBDHHYPZLHLHLGFWLCHYYTLHJXCJMSCPXSTKPNHQXSRTYXXTESYJCTLSSLSTDLLLWWYHDHRJZSFGXTSYCZYNYHTDHWJSLHTZDQDJZXXQHGYLTZPHCSQFCLNJTCLZPFSTPDYNYLGMJLLYCQHYSSHCHYLHQYQTMZYPBYWRFQYKQSYSLZDQJMPXYYSSRHZJNYWTQDFZBWWTWWRXCWHGYHXMKMYYYQMSMZHNGCEPMLQQMTCWCTMMPXJPJJHFXYYZSXZHTYBMSTSYJTTQQQYYLHYNPYQZLCYZHZWSMYLKFJXLWGXYPJYTYSYXYMZCKTTWLKSMZSYLMPWLZWXWQZSSAQSYXYRHSSNTSRAPXCPWCMGDXHXZDZYFJHGZTTSBJHGYZSZYSMYCLLLXBTYXHBBZJKSSDMALXHYCFYGMQYPJYCQXJLLLJGSLZGQLYCJCCZOTYXMTMTTLLWTGPXYMZMKLPSZZZXHKQYSXCTYJZYHXSHYXZKXLZWPSQPYHJWPJPWXQQYLXSDHMRSLZZYZWTTCYXYSZZSHBSCCSTPLWSSCJCHNLCGCHSSPHYLHFHHXJSXYLLNYLSZDHZXYLSXLWZYKCLDYAXZCMDDYSPJTQJZLNWQPSSSWCTSTSZLBLNXSMNYYMJQBQHRZWTYYDCHQLXKPZWBGQYBKFCMZWPZLLYYLSZYDWHXPSBCMLJBSCGBHXLQHYRLJXYSWXWXZSLDFHLSLYNJLZYFLYJYCDRJLFSYZFSLLCQYQFGJYHYXZLYLMSTDJCYHBZLLNWLXXYGYYHSMGDHXXHHLZZJZXCZZZCYQZFNGWPYLCPKPYYPMCLQKDGXZGGWQBDXZZKZFBXXLZXJTPJPTTBYTSZZDWSLCHZHSLTYXHQLHYXXXYYZYSWTXZKHLXZXZPYHGCHKCFSYHUTJRLXFJXPTZTWHPLYXFCRHXSHXKYXXYHZQDXQWULHYHMJTBFLKHTXCWHJFWJCFPQRYQXCYYYQYGRPYWSGSUNGWCHKZDXYFLXXHJJBYZWTSXXNCYJJYMSWZJQRMHXZWFQSYLZJZGBHYNSLBGTTCSYBYXXWXYHXYYXNSQYXMQYWRGYQLXBBZLJSYLPSYTJZYHYZAWLRORJMKSCZJXXXYXCHDYXRYXXJDTSQFXLYLTSFFYXLMTYJMJUYYYXLTZCSXQZQHZXLYYXZHDNBRXXXJCTYHLBRLMBRLLAXKYLLLJLYXXLYCRYLCJTGJCMTLZLLCYZZPZPCYAWHJJFYBDYYZSMPCKZDQYQPBPCJPDCYZMDPBCYYDYCNNPLMTMLRMFMMGWYZBSJGYGSMZQQQZTXMKQWGXLLPJGZBQCDJJJFPKJKCXBLJMSWMDTQJXLDLPPBXCWRCQFBFQJCZAHZGMYKPHYYHZYKNDKZMBPJYXPXYHLFPNYYGXJDBKXNXHJMZJXSTRSTLDXSKZYSYBZXJLXYSLBZYSLHXJPFXPQNBYLLJQKYGZMCYZZYMCCSLCLHZFWFWYXZMWSXTYNXJHPYYMCYSPMHYSMYDYSHQYZCHMJJMZCAAGCFJBBHPLYZYLXXSDJGXDHKXXTXXNBHRMLYJSLTXMRHNLXQJXYZLLYSWQGDLBJHDCGJYQYCMHWFMJYBMBYJYJWYMDPWHXQLDYGPDFXXBCGJSPCKRSSYZJMSLBZZJFLJJJLGXZGYXYXLSZQYXBEXYXHGCXBPLDYHWETTWWCJMBTXCHXYQXLLXFLYXLLJLSSFWDPZSMYJCLMWYTCZPCHQEKCQBWLCQYDPLQPPQZQFJQDJHYMMCXTXDRMJWRHXCJZYLQXDYYNHYYHRSLSRSYWWZJYMTLTLLGTQCJZYABTCKZCJYCCQLJZQXALMZYHYWLWDXZXQDLLQSHGPJFJLJHJABCQZDJGTKHSSTCYJLPSWZLXZXRWGLDLZRLZXTGSLLLLZLYXXWGDZYGBDPHZPBRLWSXQBPFDWOFMWHLYPCBJCCLDMBZPBZZLCYQXLDOMZBLZWPDWYYGDSTTHCSQSCCRSSSYSLFYBFNTYJSZDFNDPDHDZZMBBLSLCMYFFGTJJQWFTMTPJWFNLBZCMMJTGBDZLQLPYFHYYMJYLSDCHDZJWJCCTLJCLDTLJJCPDDSQDSSZYBNDBJLGGJZXSXNLYCYBJXQYCBYLZCFZPPGKCXZDZFZTJJFJSJXZBNZYJQTTYJYHTYCZHYMDJXTTMPXSPLZCDWSLSHXYPZGTFMLCJTYCBPMGDKWYCYZCDSZZYHFLYCTYGWHKJYYLSJCXGYWJCBLLCSNDDBTZBSCLYZCZZSSQDLLMQYYHFSLQLLXFTYHABXGWNYWYYPLLSDLDLLBJCYXJZMLHLJDXYYQYTDLLLBUGBFDFBBQJZZMDPJHGCLGMJJPGAEHHBWCQXAXHHHZCHXYPHJAXHLPHJPGPZJQCQZGJJZZUZDMQYYBZZPHYHYBWHAZYJHYKFGDPFQSDLZMLJXKXGALXZDAGLMDGXMWZQYXXDXXPFDMMSSYMPFMDMMKXKSYZYSHDZKXSYSMMZZZMSYDNZZCZXFPLSTMZDNMXCKJMZTYYMZMZZMSXHHDCZJEMXXKLJSTLWLSQLYJZLLZJSSDPPMHNLZJCZYHMXXHGZCJMDHXTKGRMXFWMCGMWKDTKSXQMMMFZZYDKMSCLCMPCGMHSPXQPZDSSLCXKYXTWLWJYAHZJGZQMCSNXYYMMPMLKJXMHLMLQMXCTKZMJQYSZJSYSZHSYJZJCDAJZYBSDQJZGWZQQXFKDMSDJLFWEHKZQKJPEYPZYSZCDWYJFFMZZYLTTDZZEFMZLBNPPLPLPEPSZALLTYLKCKQZKGENQLWAGYXYDPXLHSXQQWQCQXQCLHYXXMLYCCWLYMQYSKGCHLCJNSZKPYZKCQZQLJPDMDZHLASXLBYDWQLWDNBQCRYDDZTJYBKBWSZDXDTNPJDTCTQDFXQQMGNXECLTTBKPWSLCTYQLPWYZZKLPYGZCQQPLLKCCYLPQMZCZQCLJSLQZDJXLDDHPZQDLJJXZQDXYZQKZLJCYQDYJPPYPQYKJYRMPCBYMCXKLLZLLFQPYLLLMBSGLCYSSLRSYSQTMXYXZQZFDZUYSYZTFFMZZSMZQHZSSCCMLYXWTPZGXZJGZGSJSGKDDHTQGGZLLBJDZLCBCHYXYZHZFYWXYZYMSDBZZYJGTSMTFXQYXQSTDGSLNXDLRYZZLRYYLXQHTXSRTZNGZXBNQQZFMYKMZJBZYMKBPNLYZPBLMCNQYZZZSJZHJCTZKHYZZJRDYZHNPXGLFZTLKGJTCTSSYLLGZRZBBQZZKLPKLCZYSSUYXBJFPNJZZXCDWXZYJXZZDJJKGGRSRJKMSMZJLSJYWQSKYHQJSXPJZZZLSNSHRNYPZTWCHKLPSRZLZXYJQXQKYSJYCZTLQZYBBYBWZPQDWWYZCYTJCJXCKCWDKKZXSGKDZXWWYYJQYYTCYTDLLXWKCZKKLCCLZCQQDZLQLCSFQCHQHSFSMQZZLNBJJZBSJHTSZDYSJQJPDLZCDCWJKJZZLPYCGMZWDJJBSJQZSYZYHHXJPBJYDSSXDZNCGLQMBTSFSBPDZDLZNFGFJGFSMPXJQLMBLGQCYYXBQKDJJQYRFKZTJDHCZKLBSDZCFJTPLLJGXHYXZCSSZZXSTJYGKGCKGYOQXJPLZPBPGTGYJZGHZQZZLBJLSQFZGKQQJZGYCZBZQTLDXRJXBSXXPZXHYZYCLWDXJJHXMFDZPFZHQHQMQGKSLYHTYCGFRZGNQXCLPDLBZCSCZQLLJBLHBZCYPZZPPDYMZZSGYHCKCPZJGSLJLNSCDSLDLXBMSTLDDFJMKDJDHZLZXLSZQPQPGJLLYBDSZGQLBZLSLKYYHZTTNTJYQTZZPSZQZTLLJTYYLLQLLQYZQLBDZLSLYYZYMDFSZSNHLXZNCZQZPBWSKRFBSYZMTHBLGJPMCZZLSTLXSHTCSYZLZBLFEQHLXFLCJLYLJQCBZLZJHHSSTBRMHXZHJZCLXFNBGXGTQJCZTMSFZKJMSSNXLJKBHSJXNTNLZDNTLMSJXGZJYJCZXYJYJWRWWQNZTNFJSZPZSHZJFYRDJSFSZJZBJFZQZZHZLXFYSBZQLZSGYFTZDCSZXZJBQMSZKJRHYJZCKMJKHCHGTXKXQGLXPXFXTRTYLXJXHDTSJXHJZJXZWZLCQSBTXWXGXTXXHXFTSDKFJHZYJFJXRZSDLLLTQSQQZQWZXSYQTWGWBZCGZLLYZBCLMQQTZHZXZXLJFRMYZFLXYSQXXJKXRMQDZDMMYYBSQBHGZMWFWXGMXLZPYYTGZYCCDXYZXYWGSYJYZNBHPZJSQSYXSXRTFYZGRHZTXSZZTHCBFCLSYXZLZQMZLMPLMXZJXSFLBYZMYQHXJSXRXSQZZZSSLYFRCZJRCRXHHZXQYDYHXSJJHZCXZBTYNSYSXJBQLPXZQPYMLXZKYXLXCJLCYSXXZZLXDLLLJJYHZXGYJWKJRWYHCPSGNRZLFZWFZZNSXGXFLZSXZZZBFCSYJDBRJKRDHHGXJLJJTGXJXXSTJTJXLYXQFCSGSWMSBCTLQZZWLZZKXJMLTMJYHSDDBXGZHDLBMYJFRZFSGCLYJBPMLYSMSXLSZJQQHJZFXGFQFQBPXZGYYQXGZTCQWYLTLGWSGWHRLFSFGZJMGMGBGTJFSYZZGZYZAFLSSPMLPFLCWBJZCLJJMZLPJJLYMQDMYYYFBGYGYZMLYZDXQYXRQQQHSYYYQXYLJTYXFSFSLLGNQCYHYCWFHCCCFXPYLYPLLZYXXXXXKQHHXSHJZCFZSCZJXCPZWHHHHHAPYLQALPQAFYHXDYLUKMZQGGGDDESRNNZLTZGCHYPPYSQJJHCLLJTOLNJPZLJLHYMHEYDYDSQYCDDHGZUNDZCLZYZLLZNTNYZGSLHSLPJJBDGWXPCDUTJCKLKCLWKLLCASSTKZZDNQNTTLYYZSSYSSZZRYLJQKCQDHHCRXRZYDGRGCWCGZQFFFPPJFZYNAKRGYWYQPQXXFKJTSZZXSWZDDFBBXTBGTZKZNPZZPZXZPJSZBMQHKCYXYLDKLJNYPKYGHGDZJXXEAHPNZKZTZCMXCXMMJXNKSZQNMNLWBWWXJKYHCPSTMCSQTZJYXTPCTPDTNNPGLLLZSJLSPBLPLQHDTNJNLYYRSZFFJFQWDPHZDWMRZCCLODAXNSSNYZRESTYJWJYJDBCFXNMWTTBYLWSTSZGYBLJPXGLBOCLHPCBJLTMXZLJYLZXCLTPNCLCKXTPZJSWCYXSFYSZDKNTLBYJCYJLLSTGQCBXRYZXBXKLYLHZLQZLNZCXWJZLJZJNCJHXMNZZGJZZXTZJXYCYYCXXJYYXJJXSSSJSTSSTTPPGQTCSXWZDCSYFPTFBFHFBBLZJCLZZDBXGCXLQPXKFZFLSYLTUWBMQJHSZBMDDBCYSCCLDXYCDDQLYJJWMQLLCSGLJJSYFPYYCCYLTJANTJJPWYCMMGQYYSXDXQMZHSZXPFTWWZQSWQRFKJLZJQQYFBRXJHHFWJJZYQAZMYFRHCYYBYQWLPEXCCZSTYRLTTDMQLYKMBBGMYYJPRKZNPBSXYXBHYZDJDNGHPMFSGMWFZMFQMMBCMZZCJJLCNUXYQLMLRYGQZCYXZLWJGCJCGGMCJNFYZZJHYCPRRCMTZQZXHFQGTJXCCJEAQCRJYHPLQLSZDJRBCQHQDYRHYLYXJSYMHZYDWLDFRYHBPYDTSSCNWBXGLPZMLZZTQSSCPJMXXYCSJYTYCGHYCJWYRXXLFEMWJNMKLLSWTXHYYYNCMMCWJDQDJZGLLJWJRKHPZGGFLCCSCZMCBLTBHBQJXQDSPDJZZGKGLFQYWBZYZJLTSTDHQHCTCBCHFLQMPWDSHYYTQWCNZZJTLBYMBPDYYYXSQKXWYYFLXXNCWCXYPMAELYKKJMZZZBRXYYQJFLJPFHHHYTZZXSGQQMHSPGDZQWBWPJHZJDYSCQWZKTXXSQLZYYMYSDZGRXCKKUJLWPYSYSCSYZLRMLQSYLJXBCXTLWDQZPCYCYKPPPNSXFYZJJRCEMHSZMSXLXGLRWGCSTLRSXBZGBZGZTCPLUJLSLYLYMTXMTZPALZXPXJTJWTCYYZLBLXBZLQMYLXPGHDSLSSDMXMBDZZSXWHAMLCZCPJMCNHJYSNSYGCHSKQMZZQDLLKABLWJXSFMOCDXJRRLYQZKJMYBYQLYHETFJZFRFKSRYXFJTWDSXXSYSQJYSLYXWJHSNLXYYXHBHAWHHJZXWMYLJCSSLKYDZTXBZSYFDXGXZJKHSXXYBSSXDPYNZWRPTQZCZENYGCXQFJYKJBZMLJCMQQXUOXSLYXXLYLLJDZBTYMHPFSTTQQWLHOKYBLZZALZXQLHZWRRQHLSTMYPYXJJXMQSJFNBXYXYJXXYQYLTHYLQYFMLKLJTMLLHSZWKZHLJMLHLJKLJSTLQXYLMBHHLNLZXQJHXCFXXLHYHJJGBYZZKBXSCQDJQDSUJZYYHZHHMGSXCSYMXFEBCQWWRBPYYJQTYZCYQYQQZYHMWFFHGZFRJFCDPXNTQYZPDYKHJLFRZXPPXZDBBGZQSTLGDGYLCQMLCHHMFYWLZYXKJLYPQHSYWMQQGQZMLZJNSQXJQSYJYCBEHSXFSZPXZWFLLBCYYJDYTDTHWZSFJMQQYJLMQXXLLDTTKHHYBFPWTYYSQQWNQWLGWDEBZWCMYGCULKJXTMXMYJSXHYBRWFYMWFRXYQMXYSZTZZTFYKMLDHQDXWYYNLCRYJBLPSXCXYWLSPRRJWXHQYPHTYDNXHHMMYWYTZCSQMTSSCCDALWZTCPQPYJLLQZYJSWXMZZMMYLMXCLMXCZMXMZSQTZPPQQBLPGXQZHFLJJHYTJSRXWZXSCCDLXTYJDCQJXSLQYCLZXLZZXMXQRJMHRHZJBHMFLJLMLCLQNLDXZLLLPYPSYJYSXCQQDCMQJZZXHNPNXZMEKMXHYKYQLXSXTXJYYHWDCWDZHQYYBGYBCYSCFGPSJNZDYZZJZXRZRQJJYMCANYRJTLDPPYZBSTJKXXZYPFDWFGZZRPYMTNGXZQBYXNBUFNQKRJQZMJEGRZGYCLKXZDSKKNSXKCLJSPJYYZLQQJYBZSSQLLLKJXTBKTYLCCDDBLSPPFYLGYDTZJYQGGKQTTFZXBDKTYYHYBBFYTYYBCLPDYTGDHRYRNJSPTCSNYJQHKLLLZSLYDXXWBCJQSPXBPJZJCJDZFFXXBRMLAZHCSNDLBJDSZBLPRZTSWSBXBCLLXXLZDJZSJPYLYXXYFTFFFBHJJXGBYXJPMMMPSSJZJMTLYZJXSWXTYLEDQPJMYGQZJGDJLQJWJQLLSJGJGYGMSCLJJXDTYGJQJQJCJZCJGDZZSXQGSJGGCXHQXSNQLZZBXHSGZXCXYLJXYXYYDFQQJHJFXDHCTXJYRXYSQTJXYEFYYSSYYJXNCYZXFXMSYSZXYYSCHSHXZZZGZZZGFJDLTYLNPZGYJYZYYQZPBXQBDZTZCZYXXYHHSQXSHDHGQHJHGYWSZTMZMLHYXGEBTYLZKQWYTJZRCLEKYSTDBCYKQQSAYXCJXWWGSBHJYZYDHCSJKQCXSWXFLTYNYZPZCCZJQTZWJQDZZZQZLJJXLSBHPYXXPSXSHHEZTXFPTLQYZZXHYTXNCFZYYHXGNXMYWXTZSJPTHHGYMXMXQZXTSBCZYJYXXTYYZYPCQLMMSZMJZZLLZXGXZAAJZYXJMZXWDXZSXZDZXLEYJJZQBHZWZZZQTZPSXZTDSXJJJZNYAZPHXYYSRNQDTHZHYYKYJHDZXZLSWCLYBZYECWCYCRYLCXNHZYDZYDYJDFRJJHTRSQTXYXJRJHOJYNXELXSFSFJZGHPZSXZSZDZCQZBYYKLSGSJHCZSHDGQGXYZGXCHXZJWYQWGYHKSSEQZZNDZFKWYSSTCLZSTSYMCDHJXXYWEYXCZAYDMPXMDSXYBSQMJMZJMTZQLPJYQZCGQHXJHHLXXHLHDLDJQCLDWBSXFZZYYSCHTYTYYBHECXHYKGJPXHHYZJFXHWHBDZFYZBCAPNPGNYDMSXHMMMMAMYNBYJTMPXYYMCTHJBZYFCGTYHWPHFTWZZEZSBZEGPFMTSKFTYCMHFLLHGPZJXZJGZJYXZSBBQSCZZLZCCSTPGXMJSFTCCZJZDJXCYBZLFCJSYZFGSZLYBCWZZBYZDZYPSWYJZXZBDSYUXLZZBZFYGCZXBZHZFTPBGZGEJBSTGKDMFHYZZJHZLLZZGJQZLSFDJSSCBZGPDLFZFZSZYZYZSYGCXSNXXCHCZXTZZLJFZGQSQYXZJQDCCZTQCDXZJYQJQCHXZTDLGSCXZSYQJQTZWLQDQZTQCHQQJZYEZZZPBWKDJFCJPZTYPQYQTTYNLMBDKTJZPQZQZZFPZSBNJLGYJDXJDZZKZGQKXDLPZJTCJDQBXDJQJSTCKNXBXZMSLYJCQMTJQWWCJQNJNLLLHJCWQTBZQYDZCZPZZDZYDDCYZZZCCJTTJFZDPRRTZTJDCQTQZDTJNPLZBCLLCTZSXKJZQZPZLBZRBTJDCXFCZDBCCJJLTQQPLDCGZDBBZJCQDCJWYNLLZYZCCDWLLXWZLXRXNTQQCZXKQLSGDFQTDDGLRLAJJTKUYMKQLLTZYTDYYCZGJWYXDXFRSKSTQTENQMRKQZHHQKDLDAZFKYPBGGPZREBZZYKZZSPEGJXGYKQZZZSLYSYYYZWFQZYLZZLZHWCHKYPQGNPGBLPLRRJYXCCSYYHSFZFYBZYYTGZXYLXCZWXXZJZBLFFLGSKHYJZEYJHLPLLLLCZGXDRZELRHGKLZZYHZLYQSZZJZQLJZFLNBHGWLCZCFJYSPYXZLZLXGCCPZBLLCYBBBBUBBCBPCRNNZCZYRBFSRLDCGQYYQXYGMQZWTZYTYJXYFWTEHZZJYWLCCNTZYJJZDEDPZDZTSYQJHDYMBJNYJZLXTSSTPHNDJXXBYXQTZQDDTJTDYYTGWSCSZQFLSHLGLBCZPHDLYZJYCKWTYTYLBNYTSDSYCCTYSZYYEBHEXHQDTWNYGYCLXTSZYSTQMYGZAZCCSZZDSLZCLZRQXYYELJSBYMXSXZTEMBBLLYYLLYTDQYSHYMRQWKFKBFXNXSBYCHXBWJYHTQBPBSBWDZYLKGZSKYHXQZJXHXJXGNLJKZLYYCDXLFYFGHLJGJYBXQLYBXQPQGZTZPLNCYPXDJYQYDYMRBESJYYHKXXSTMXRCZZYWXYQYBMCLLYZHQYZWQXDBXBZWZMSLPDMYSKFMZKLZCYQYCZLQXFZZYDQZPZYGYJYZMZXDZFYFYTTQTZHGSPCZMLCCYTZXJCYTJMKSLPZHYSNZLLYTPZCTZZCKTXDHXXTQCYFKSMQCCYYAZHTJPCYLZLYJBJXTPNYLJYYNRXSYLMMNXJSMYBCSYSYLZYLXJJQYLDZLPQBFZZBLFNDXQKCZFYWHGQMRDSXYCYTXNQQJZYYPFZXDYZFPRXEJDGYQBXRCNFYYQPGHYJDYZXGRHTKYLNWDZNTSMPKLBTHBPYSZBZTJZSZZJTYYXZPHSSZZBZCZPTQFZMYFLYPYBBJQXZMXXDJMTSYSKKBJZXHJCKLPSMKYJZCXTMLJYXRZZQSLXXQPYZXMKYXXXJCLJPRMYYGADYSKQLSNDHYZKQXZYZTCGHZTLMLWZYBWSYCTBHJHJFCWZTXWYTKZLXQSHLYJZJXTMPLPYCGLTBZZTLZJCYJGDTCLKLPLLQPJMZPAPXYZLKKTKDZCZZBNZDYDYQZJYJGMCTXLTGXSZLMLHBGLKFWNWZHDXUHLFMKYSLGXDTWWFRJEJZTZHYDXYKSHWFZCQSHKTMQQHTZHYMJDJSKHXZJZBZZXYMPAGQMSTPXLSKLZYNWRTSQLSZBPSPSGZWYHTLKSSSWHZZLYYTNXJGMJSZSUFWNLSOZTXGXLSAMMLBWLDSZYLAKQCQCTMYCFJBSLXCLZZCLXXKSBZQCLHJPSQPLSXXCKSLNHPSFQQYTXYJZLQLDXZQJZDYYDJNZPTUZDSKJFSLJHYLZSQZLBTXYDGTQFDBYAZXDZHZJNHHQBYKNXJJQCZMLLJZKSPLDYCLBBLXKLELXJLBQYCXJXGCNLCQPLZLZYJTZLJGYZDZPLTQCSXFDMNYCXGBTJDCZNBGBQYQJWGKFHTNPYQZQGBKPBBYZMTJDYTBLSQMPSXTBNPDXKLEMYYCJYNZCTLDYKZZXDDXHQSHDGMZSJYCCTAYRZLPYLTLKXSLZCGGEXCLFXLKJRTLQJAQZNCMBYDKKCXGLCZJZXJHPTDJJMZQYKQSECQZDSHHADMLZFMMZBGNTJNNLGBYJBRBTMLBYJDZXLCJLPLDLPCQDHLXZLYCBLCXZZJADJLNZMMSSSMYBHBSQKBHRSXXJMXSDZNZPXLGBRHWGGFCXGMSKLLTSJYYCQLTSKYWYYHYWXBXQYWPYWYKQLSQPTNTKHQCWDQKTWPXXHCPTHTWUMSSYHBWCRWXHJMKMZNGWTMLKFGHKJYLSYYCXWHYECLQHKQHTTQKHFZLDXQWYZYYDESBPKYRZPJFYYZJCEQDZZDLATZBBFJLLCXDLMJSSXEGYGSJQXCWBXSSZPDYZCXDNYXPPZYDLYJCZPLTXLSXYZYRXCYYYDYLWWNZSAHJSYQYHGYWWAXTJZDAXYSRLTDPSSYYFNEJDXYZHLXLLLZQZSJNYQYQQXYJGHZGZCYJCHZLYCDSHWSHJZYJXCLLNXZJJYYXNFXMWFPYLCYLLABWDDHWDXJMCXZTZPMLQZHSFHZYNZTLLDYWLSLXHYMMYLMBWWKYXYADTXYLLDJPYBPWUXJMWMLLSAFDLLYFLBHHHBQQLTZJCQJLDJTFFKMMMBYTHYGDCQRDDWRQJXNBYSNWZDBYYTBJHPYBYTTJXAAHGQDQTMYSTQXKBTZPKJLZRBEQQSSMJJBDJOTGTBXPGBKTLHQXJJJCTHXQDWJLWRFWQGWSHCKRYSWGFTGYGBXSDWDWRFHWYTJJXXXJYZYSLPYYYPAYXHYDQKXSHXYXGSKQHYWFDDDPPLCJLQQEEWXKSYYKDYPLTJTHKJLTCYYHHJTTPLTZZCDLTHQKZXQYSTEEYWYYZYXXYYSTTJKLLPZMCYHQGXYHSRMBXPLLNQYDQHXSXXWGDQBSHYLLPJJJTHYJKYPPTHYYKTYEZYENMDSHLCRPQFDGFXZPSFTLJXXJBSWYYSKSFLXLPPLBBBLBSFXFYZBSJSSYLPBBFFFFSSCJDSTZSXZRYYSYFFSYZYZBJTBCTSBSDHRTJJBYTCXYJEYLXCBNEBJDSYXYKGSJZBXBYTFZWGENYHHTHZHHXFWGCSTBGXKLSXYWMTMBYXJSTZSCDYQRCYTWXZFHMYMCXLZNSDJTTTXRYCFYJSBSDYERXJLJXBBDEYNJGHXGCKGSCYMBLXJMSZNSKGXFBNBPTHFJAAFXYXFPXMYPQDTZCXZZPXRSYWZDLYBBKTYQPQJPZYPZJZNJPZJLZZFYSBTTSLMPTZRTDXQSJEHBZYLZDHLJSQMLHTXTJECXSLZZSPKTLZKQQYFSYGYWPCPQFHQHYTQXZKRSGTTSQCZLPTXCDYYZXSQZSLXLZMYCPCQBZYXHBSXLZDLTCDXTYLZJYYZPZYZLTXJSJXHLPMYTXCQRBLZSSFJZZTNJYTXMYJHLHPPLCYXQJQQKZZSCPZKSWALQSBLCCZJSXGWWWYGYKTJBBZTDKHXHKGTGPBKQYSLPXPJCKBMLLXDZSTBKLGGQKQLSBKKTFXRMDKBFTPZFRTBBRFERQGXYJPZSSTLBZTPSZQZSJDHLJQLZBPMSMMSXLQQNHKNBLRDDNXXDHDDJCYYGYLXGZLXSYGMQQGKHBPMXYXLYTQWLWGCPBMQXCYZYDRJBHTDJYHQSHTMJSBYPLWHLZFFNYPMHXXHPLTBQPFBJWQDBYGPNZTPFZJGSDDTQSHZEAWZZYLLTYYBWJKXXGHLFKXDJTMSZSQYNZGGSWQSPHTLSSKMCLZXYSZQZXNCJDQGZDLFNYKLJCJLLZLMZZNHYDSSHTHZZLZZBBHQZWWYCRZHLYQQJBEYFXXXWHSRXWQHWPSLMSSKZTTYGYQQWRSLALHMJTQJSMXQBJJZJXZYZKXBYQXBJXSHZTSFJLXMXZXFGHKZSZGGYLCLSARJYHSLLLMZXELGLXYDJYTLFBHBPNLYZFBBHPTGJKWETZHKJJXZXXGLLJLSTGSHJJYQLQZFKCGNNDJSSZFDBCTWWSEQFHQJBSAQTGYPQLBXBMMYWXGSLZHGLZGQYFLZBYFZJFRYSFMBYZHQGFWZSYFYJJPHZBYYZFFWODGRLMFTWLBZGYCQXCDJYGZYYYYTYTYDWEGAZYHXJLZYYHLRMGRXXZCLHNELJJTJTPWJYBJJBXJJTJTEEKHWSLJPLPSFYZPQQBDLQJJTYYQLYZKDKSQJYYQZLDQTGJQYZJSUCMRYQTHTEJMFCTYHYPKMHYZWJDQFHYYXWSHCTXRLJHQXHCCYYYJLTKTTYTMXGTCJTZAYYOCZLYLBSZYWJYTSJYHBYSHFJLYGJXXTMZYYLTXXYPZLXYJZYZYYPNHMYMDYYLBLHLSYYQQLLNJJYMSOYQBZGDLYXYLCQYXTSZEGXHZGLHWBLJHEYXTWQMAKBPQCGYSHHEGQCMWYYWLJYJHYYZLLJJYLHZYHMGSLJLJXCJJYCLYCJPCPZJZJMMYLCQLNQLJQJSXYJMLSZLJQLYCMMHCFMMFPQQMFYLQMCFFQMMMMHMZNFHHJGTTHHKHSLNCHHYQDXTMMQDCYZYXYQMYQYLTDCYYYZAZZCYMZYDLZFFFMMYCQZWZZMABTBYZTDMNZZGGDFTYPCGQYTTSSFFWFDTZQSSYSTWXJHXYTSXXYLBYQHWWKXHZXWZNNZZJZJJQJCCCHYYXBZXZCYZTLLCQXYNJYCYYCYNZZQYYYEWYCZDCJYCCHYJLBTZYYCQWMPWPYMLGKDLDLGKQQBGYCHJXY";
//此处收录了375个多音字
    var oMultiDiff={"19969":"DZ","19975":"WM","19988":"QJ","20048":"YL","20056":"SC","20060":"NM","20094":"QG","20127":"QJ","20167":"QC","20193":"YG","20250":"KH","20256":"ZC","20282":"SC","20285":"QJG","20291":"TD","20314":"YD","20340":"NE","20375":"TD","20389":"YJ","20391":"CZ","20415":"PB","20446":"YS","20447":"SQ","20504":"TC","20608":"KG","20854":"QJ","20857":"ZC","20911":"PF","20504":"TC","20608":"KG","20854":"QJ","20857":"ZC","20911":"PF","20985":"AW","21032":"PB","21048":"XQ","21049":"SC","21089":"YS","21119":"JC","21242":"SB","21273":"SC","21305":"YP","21306":"QO","21330":"ZC","21333":"SDC","21345":"QK","21378":"CA","21397":"SC","21414":"XS","21442":"SC","21477":"JG","21480":"TD","21484":"ZS","21494":"YX","21505":"YX","21512":"HG","21523":"XH","21537":"PB","21542":"PF","21549":"KH","21571":"E","21574":"DA","21588":"TD","21589":"O","21618":"ZC","21621":"KHA","21632":"ZJ","21654":"KG","21679":"LKG","21683":"KH","21710":"A","21719":"YH","21734":"WOE","21769":"A","21780":"WN","21804":"XH","21834":"A","21899":"ZD","21903":"RN","21908":"WO","21939":"ZC","21956":"SA","21964":"YA","21970":"TD","22003":"A","22031":"JG","22040":"XS","22060":"ZC","22066":"ZC","22079":"MH","22129":"XJ","22179":"XA","22237":"NJ","22244":"TD","22280":"JQ","22300":"YH","22313":"XW","22331":"YQ","22343":"YJ","22351":"PH","22395":"DC","22412":"TD","22484":"PB","22500":"PB","22534":"ZD","22549":"DH","22561":"PB","22612":"TD","22771":"KQ","22831":"HB","22841":"JG","22855":"QJ","22865":"XQ","23013":"ML","23081":"WM","23487":"SX","23558":"QJ","23561":"YW","23586":"YW","23614":"YW","23615":"SN","23631":"PB","23646":"ZS","23663":"ZT","23673":"YG","23762":"TD","23769":"ZS","23780":"QJ","23884":"QK","24055":"XH","24113":"DC","24162":"ZC","24191":"GA","24273":"QJ","24324":"NL","24377":"TD","24378":"QJ","24439":"PF","24554":"ZS","24683":"TD","24694":"WE","24733":"LK","24925":"TN","25094":"ZG","25100":"XQ","25103":"XH","25153":"PB","25170":"PB","25179":"KG","25203":"PB","25240":"ZS","25282":"FB","25303":"NA","25324":"KG","25341":"ZY","25373":"WZ","25375":"XJ","25384":"A","25457":"A","25528":"SD","25530":"SC","25552":"TD","25774":"ZC","25874":"ZC","26044":"YW","26080":"WM","26292":"PB","26333":"PB","26355":"ZY","26366":"CZ","26397":"ZC","26399":"QJ","26415":"ZS","26451":"SB","26526":"ZC","26552":"JG","26561":"TD","26588":"JG","26597":"CZ","26629":"ZS","26638":"YL","26646":"XQ","26653":"KG","26657":"XJ","26727":"HG","26894":"ZC","26937":"ZS","26946":"ZC","26999":"KJ","27099":"KJ","27449":"YQ","27481":"XS","27542":"ZS","27663":"ZS","27748":"TS","27784":"SC","27788":"ZD","27795":"TD","27812":"O","27850":"PB","27852":"MB","27895":"SL","27898":"PL","27973":"QJ","27981":"KH","27986":"HX","27994":"XJ","28044":"YC","28065":"WG","28177":"SM","28267":"QJ","28291":"KH","28337":"ZQ","28463":"TL","28548":"DC","28601":"TD","28689":"PB","28805":"JG","28820":"QG","28846":"PB","28952":"TD","28975":"ZC","29100":"A","29325":"QJ","29575":"SL","29602":"FB","30010":"TD","30044":"CX","30058":"PF","30091":"YSP","30111":"YN","30229":"XJ","30427":"SC","30465":"SX","30631":"YQ","30655":"QJ","30684":"QJG","30707":"SD","30729":"XH","30796":"LG","30917":"PB","31074":"NM","31085":"JZ","31109":"SC","31181":"ZC","31192":"MLB","31293":"JQ","31400":"YX","31584":"YJ","31896":"ZN","31909":"ZY","31995":"XJ","32321":"PF","32327":"ZY","32418":"HG","32420":"XQ","32421":"HG","32438":"LG","32473":"GJ","32488":"TD","32521":"QJ","32527":"PB","32562":"ZSQ","32564":"JZ","32735":"ZD","32793":"PB","33071":"PF","33098":"XL","33100":"YA","33152":"PB","33261":"CX","33324":"BP","33333":"TD","33406":"YA","33426":"WM","33432":"PB","33445":"JG","33486":"ZN","33493":"TS","33507":"QJ","33540":"QJ","33544":"ZC","33564":"XQ","33617":"YT","33632":"QJ","33636":"XH","33637":"YX","33694":"WG","33705":"PF","33728":"YW","33882":"SR","34067":"WM","34074":"YW","34121":"QJ","34255":"ZC","34259":"XL","34425":"JH","34430":"XH","34485":"KH","34503":"YS","34532":"HG","34552":"XS","34558":"YE","34593":"ZL","34660":"YQ","34892":"XH","34928":"SC","34999":"QJ","35048":"PB","35059":"SC","35098":"ZC","35203":"TQ","35265":"JX","35299":"JX","35782":"SZ","35828":"YS","35830":"E","35843":"TD","35895":"YG","35977":"MH","36158":"JG","36228":"QJ","36426":"XQ","36466":"DC","36710":"JC","36711":"ZYG","36767":"PB","36866":"SK","36951":"YW","37034":"YX","37063":"XH","37218":"ZC","37325":"ZC","38063":"PB","38079":"TD","38085":"QY","38107":"DC","38116":"TD","38123":"YD","38224":"HG","38241":"XTC","38271":"ZC","38415":"YE","38426":"KH","38461":"YD","38463":"AE","38466":"PB","38477":"XJ","38518":"YT","38551":"WK","38585":"ZC","38704":"XS","38739":"LJ","38761":"GJ","38808":"SQ","39048":"JG","39049":"XJ","39052":"HG","39076":"CZ","39271":"XT","39534":"TD","39552":"TD","39584":"PB","39647":"SB","39730":"LG","39748":"TPB","40109":"ZQ","40479":"ND","40516":"HG","40536":"HG","40583":"QJ","40765":"YQ","40784":"QJ","40840":"YK","40863":"QJG"};
//参数,中文字符串
//返回值:拼音首字母串数组
    function makePy(str){
        if(typeof(str) != "string")
            throw new Error(-1,"函数makePy需要字符串类型参数!");
        var arrResult = new Array(); //保存中间结果的数组
        for(var i=0,len=str.length;i<len;i++){
//获得unicode码
            var ch = str.charAt(i);
//检查该unicode码是否在处理范围之内,在则返回该码对映汉字的拼音首字母,不在则调用其它函数处理
            arrResult.push(checkCh(ch));
        }
//处理arrResult,返回所有可能的拼音首字母串数组
        return mkRslt(arrResult);
    }
    function checkCh(ch){
        var uni = ch.charCodeAt(0);
//如果不在汉字处理范围之内,返回原字符,也可以调用自己的处理函数
        if(uni > 40869 || uni < 19968)
            return ch; //dealWithOthers(ch);
//检查是否是多音字,是按多音字处理,不是就直接在strChineseFirstPY字符串中找对应的首字母
        return (oMultiDiff[uni]?oMultiDiff[uni]:(strChineseFirstPY.charAt(uni-19968)));
    }
    function mkRslt(arr){
        var arrRslt = [""];
        for(var i=0,len=arr.length;i<len;i++){
            var str = arr[i];
            var strlen = str.length;
            if(strlen == 1){
                for(var k=0;k<arrRslt.length;k++){
                    arrRslt[k] += str;
                }
            }else{
                var tmpArr = arrRslt.slice(0);
                arrRslt = [];
                for(k=0;k<strlen;k++){
//复制一个相同的arrRslt
                    var tmp = tmpArr.slice(0);
//把当前字符str[k]添加到每个元素末尾
                    for(var j=0;j<tmp.length;j++){
                        tmp[j] += str.charAt(k);
                    }
//把复制并修改后的数组连接到arrRslt上
                    arrRslt = arrRslt.concat(tmp);
                }
            }
        }
        return arrRslt;
    }
//两端去空格函数
    String.prototype.trim = function() {    return this.replace(/(^\s*)|(\s*$)/g,""); };

    var x,y,scrollX,scrollY;
    $('#borough').on('click','li.borough>a',function(e){
        e.preventDefault();
        //获取鼠标相对文档点击坐标，实现板块框可变移动
        scrollX=document.documentElement.scrollLeft||document.body.scrollLeft;
        scrollY=document.documentElement.scrollTop||document.body.scrollTop;
        x=e.pageX+33+'px'||e.clientX+scrollX+33+'px';
        y=e.pageY-30+'px'||e.clientY+scrollY-30+'px';
        if(parseFloat(x)>735){
            $('#plate>.caret-left').hide();
            $('#plate>.caret-right').show();
            x=e.pageX+33-656+'px'||e.clientX+scrollX+33-656+'px';
        }else{
            $('#plate>.caret-left').show();
            $('#plate>.caret-right').hide();
        }
        //固定板块弹出框的上下位置
        if(parseFloat(y)>171&&parseFloat(y)<183){
            y=178+'px';
        }else if(parseFloat(y)>198&&parseFloat(y)<213){
            y=207+'px';
        }
        $('#plate').css({
            left:x,
            top:y
        });
        var boroughID=$(e.target).attr('id');//区域点击获取其id
        $.ajax({
            url:saleUrl+'getHotPlate.do',
            type:'POST',
            data:{
                boroughID:boroughID	//是	string	区域ID
            },
            success:function(data){
                var limitPlate,AHtml='',BHtml='',CHtml='',DHtml='',EHtml='',FHtml='',GHtml='',HHtml='',IHtml='',JHtml='',KHtml='',LHtml='',MHtml='',NHtml='',OHtml='',PHtml='',QHtml='',RHtml='',SHtml='',THtml='',UHtml='',VHtml='',WHtml='',XHtml='',YHtml='',ZHtml='';
                var aHtml='<li class="plate"><span>A</span></li>';
                var bHtml='<li class="plate"><span>B</span></li>';
                var cHtml='<li class="plate"><span>C</span></li>';
                var dHtml='<li class="plate"><span>D</span></li>';
                var eHtml='<li class="plate"><span>E</span></li>';
                var fHtml='<li class="plate"><span>F</span></li>';
                var gHtml='<li class="plate"><span>G</span></li>';
                var hHtml='<li class="plate"><span>H</span></li>';
                var iHtml='<li class="plate"><span>I</span></li>';
                var jHtml='<li class="plate"><span>J</span></li>';
                var kHtml='<li class="plate"><span>K</span></li>';
                var lHtml='<li class="plate"><span>L</span></li>';
                var mHtml='<li class="plate"><span>M</span></li>';
                var nHtml='<li class="plate"><span>N</span></li>';
                var oHtml='<li class="plate"><span>O</span></li>';
                var pHtml='<li class="plate"><span>P</span></li>';
                var qHtml='<li class="plate"><span>Q</span></li>';
                var rHtml='<li class="plate"><span>R</span></li>';
                var sHtml='<li class="plate"><span>S</span></li>';
                var tHtml='<li class="plate"><span>T</span></li>';
                var uHtml='<li class="plate"><span>U</span></li>';
                var vHtml='<li class="plate"><span>V</span></li>';
                var wHtml='<li class="plate"><span>W</span></li>';
                var xHtml='<li class="plate"><span>X</span></li>';
                var yHtml='<li class="plate"><span>Y</span></li>';
                var zHtml='<li class="plate"><span>Z</span></li>';
                limitPlate=data.data;
                if(!limitPlate){
                    return;
                }
                $.each(limitPlate,function(i){
                    var str = limitPlate[i].PlateName.trim();
                    if(str == "") return;
                    var arrRslt = makePy(str);
                    var firstWord=arrRslt[0].slice(0,1);
                    if(firstWord=='A'){
                        AHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='B'){
                        BHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='C'){
                        CHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='D'){
                        DHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='E'){
                        EHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='F'){
                        FHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='G'){
                        GHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='H'){
                        HHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='I'){
                        IHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='J'){
                        JHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='K'){
                        KHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='L'){
                        LHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='M'){
                        MHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='N'){
                        NHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='O'){
                        OHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='P'){
                        PHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='Q'){
                        QHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='R'){
                        RHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='S'){
                        SHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='T'){
                        THtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='U'){
                        UHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='V'){
                        VHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='W'){
                        WHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='X'){
                        XHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='Y'){
                        YHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }else if(firstWord=='Z'){
                        ZHtml+=`
                          <li class="plate"><a href="#" id="${limitPlate[i].ID}">${limitPlate[i].PlateName}</a></li>
                        `;
                    }
                });
                var allHtml=`
                     <li class="active"><a href="#">全部</a></li>
                `;
                if(AHtml==''){
                    aHtml='';
                }
                if(BHtml==''){
                    bHtml='';
                }
                if(CHtml==''){
                    cHtml='';
                }
                if(DHtml==''){
                    dHtml='';
                }
                if(EHtml==''){
                    eHtml='';
                }
                if(FHtml==''){
                    fHtml='';
                }
                if(GHtml==''){
                    gHtml='';
                }
                if(HHtml==''){
                    hHtml='';
                }
                if(IHtml==''){
                    iHtml='';
                }
                if(JHtml==''){
                    jHtml='';
                }
                if(KHtml==''){
                    kHtml='';
                }
                if(LHtml==''){
                    lHtml='';
                }
                if(MHtml==''){
                    mHtml='';
                }
                if(NHtml==''){
                    nHtml='';
                }
                if(OHtml==''){
                    oHtml='';
                }
                if(PHtml==''){
                    pHtml='';
                }
                if(QHtml==''){
                    qHtml='';
                }
                if(RHtml==''){
                    rHtml='';
                }
                if(SHtml==''){
                    sHtml='';
                }
                if(THtml==''){
                    tHtml='';
                }
                if(UHtml==''){
                    uHtml='';
                }
                if(VHtml==''){
                    vHtml='';
                }
                if(WHtml==''){
                    wHtml='';
                }
                if(XHtml==''){
                    xHtml='';
                }
                if(YHtml==''){
                    yHtml='';
                }
                if(ZHtml==''){
                    zHtml='';
                }
                $('#plateTotal').html(allHtml+aHtml+AHtml+bHtml+BHtml+cHtml+CHtml+dHtml+DHtml+eHtml+EHtml+fHtml+FHtml+gHtml+GHtml+hHtml+HHtml+iHtml+IHtml+jHtml+JHtml+kHtml+KHtml+lHtml+LHtml+mHtml+MHtml+nHtml+NHtml+oHtml+OHtml+pHtml+PHtml+qHtml+QHtml+rHtml+RHtml+sHtml+SHtml+tHtml+THtml+uHtml+UHtml+vHtml+VHtml+wHtml+WHtml+xHtml+XHtml+yHtml+YHtml+zHtml+ZHtml);
            },
            error:function(){
                alert('服务器内部出错了')
            }
        });
    });
    //点击空白处板块隐藏
    $(document).click(function(e){
        var _con=$('#plate,#borough');//设置目标区域
        if(!_con.is(e.target)&&_con.has(e.target).length===0){
            $('#plate').hide(500);
        }
    });
});